language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: jfLGfR3IVQRkBSqNkbh19KtYAbyEm0+y/9Mlbf9Myu7NgkyJEGmj9j9iFZ2zJjUrVUI3JcUBTFBIDngHnTtVKa75STNtcfxxP+XTM45YKSU7s0ef5/8uhzE1ImLpYkTRue9G5sHtQ3Hiv11UJVaNOAN5/XD+KvSJmKpFOgRjunA=
  - secure: LosFmjc40zvadAiCpwM+TbmzIzL5nI7/yA6odjfnzU3wEF1Mcd+ot9K/U7OpUf9c9i39QzI425zGChCwI4pcWww7B45w3ZrBGrepvSx+tNR0A5MtRova2k4IJhVm1EbxdFfWDv7vDLvdNUeNLazm2xWr5djK2mI0GHl+R4J35IY=
